apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employee-management-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohdsuhel786/EmployeeManagementService.git
    targetRevision: main        # or dev branch if you have one
    path: k8s/descriptive
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
