apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hrms-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohdsuhel786/EmployeeManagementService.git
    targetRevision: main
    path: k8s/descriptive/k8s-all-services-prod.yaml
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
