jwt:
  secret: dTdxIUE5ZEBMMHBAUTJyJFM1dl5XOHoqQjFlJkc0aEo=

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8089
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth(?<segment>/?.*), /api/auth${segment}

        - id: user-service
          uri: http://user-service:8088
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>/?.*), /api/users${segment}
            - name: JwtAuthFilter

        - id: employee-service
          uri: http://employee-service:8086
          predicates:
            - Path=/employees/**
          filters:
            - RewritePath=/employees(?<segment>/?.*), /api/employees${segment}
            - name: JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true




#jwt:
#  secret: dTdxIUE5ZEBMMHBAUTJyJFM1dl5XOHoqQjFlJkc0aEo=
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
##      defaultZone: http://localhost:8761/eureka/
##      defaultZone: http://service-registry:8761/eureka/
#  instance:
#    prefer-ip-address: true
#
#
#
#
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**
#          filters:
#            - RewritePath=/users(?<segment>/?.*), /api/users${segment}
#            - name: JwtAuthFilter
#
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**
#          filters:
#            - RewritePath=/auth(?<segment>/?.*), /api/auth${segment}
#
#        - id: employee-service
#          uri: lb://employee-service
#          predicates:
#            - Path=/employees/**
#          filters:
#            - RewritePath=/employees(?<segment>/?.*), /api/employees${segment}
#            - name: JwtAuthFilter
#





#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: user-service
#              uri: http://localhost:8088
#              predicates:
#                - Path=/users, /users/**
#              filters:
#                - RewritePath=/users(?<segment>/?.*), /api/users${segment}
#                - name: JwtAuthFilter
#
#            - id: auth-service
#              uri: http://localhost:8089
#              predicates:
#                - Path=/auth, /auth/**
#              filters:
#                - RewritePath=/auth(?<segment>/?.*), /api/auth${segment}
#
#            - id: order-service
#              uri: http://localhost:8087
#              predicates:
#                - Path=/orders, /orders/**
#              filters:
#                - RewritePath=/orders(?<segment>/?.*), /api/orders${segment}
#                - name: JwtAuthFilter
#
#            - id: plant-service
#              uri: http://localhost:8086
#              predicates:
#                - Path=/plants, /plants/**
#              filters:
#                - RewritePath=/plants(?<segment>/?.*), /api/plants${segment}
#                - name: JwtAuthFilter


#
#logging:
#  level:
#    org.springframework.cloud.gateway:DEBUG
#        - id: user-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/user-service/**
#          filters:
#            - StripPrefix=1
#            - name: JwtAuthFilter
