spring:
  application:
    name: api-gateway
  profiles: prod

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8088
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>/?.*), /api/users${segment}
            - name: JwtAuthFilter

        - id: auth-service
          uri: http://auth-service:8089
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth(?<segment>/?.*), /api/auth${segment}

        - id: employee-service
          uri: http://employee-service:8086
          predicates:
            - Path=/employees/**
          filters:
            - RewritePath=/employees(?<segment>/?.*), /api/employees${segment}
            - name: JwtAuthFilter
