name: EmployeeManagementService CI/CD

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch to build'
        default: 'main'
      env:
        description: 'Environment to deploy'
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  detect-services:
    runs-on: [self-hosted, windows]
    outputs:
      services-json: ${{ steps.set-output.outputs.services-json }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed services
        id: set-output
        shell: powershell
        run: |
          $services = "service-registry,api-gateway,auth-service,user-service,employee-service".Split(",")
          git fetch --depth=2 origin main
          $changed = @()
          foreach ($svc in $services) {
              if (git diff --name-only HEAD~1 HEAD | Select-String -Pattern "^$svc/") {
                  $changed += $svc
              }
          }
          if ($changed.Count -eq 0) {
              Write-Host "No changes detected. Building all services."
              $changed = $services
          }
          Write-Host "Changed services: $($changed -join ',')"
          $json = ($changed | ForEach-Object { "`"$_`"" }) -join ','
          $json = "[$json]"
          Write-Host "services-json=$json" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

  build-and-deploy:
    needs: detect-services
    runs-on: [self-hosted, windows]
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect-services.outputs.services-json) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build Docker image
        shell: powershell
        run: |
          Write-Host "Building Docker image for ${{ matrix.service }}"
          Push-Location "$Env:BASE_PATH\${{ matrix.service }}"
          & mvn -T 1C clean package -DskipTests jib:dockerBuild "-Djib.to.image=${{ matrix.service }}:latest"
          Pop-Location

      - name: Optional Docker push
        if: env.DOCKER_REGISTRY != ''
        shell: powershell
        run: |
          docker tag ${{ matrix.service }}:latest $Env:DOCKER_REGISTRY/${{ matrix.service }}:latest
          docker push $Env:DOCKER_REGISTRY/${{ matrix.service }}:latest

      - name: Trigger ArgoCD sync
        if: env.ARGOCD_SERVER != ''
        shell: powershell
        run: |
          $appName = if ("${{ github.event.inputs.env }}" -eq "prod") { "employee-management-prod" } else { "employee-management-dev" }
          argocd login $Env:ARGOCD_SERVER --grpc-web --auth-token $Env:ARGOCD_TOKEN
          argocd app sync $appName --grpc-web
          Write-Host "Triggered ArgoCD sync for $appName"
